site_name: Fairness ML
nav:
  - Overview: index.md
  - Bias Detection: bias_detection.md
  - Bias Mitigation: bias_mitigation.md
  - Explainability: explainability.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  # logo: images/logo.png
  # favicon: images/favicon.ico